{
    pkgs ? import <nixpkgs> { },
    useMold ? false,
    # targetTriple ? "x86_64-pc-windows-msvc",
    targetTriple ? "x86_64-unknown-linux-gnu",
}:

let
    lib = pkgs.lib;
    # <https://github.com/NixOS/nixpkgs/issues/250898#issuecomment-1689972902>
    mkShell =
        if useMold then
            pkgs.mkShell.override { stdenv = pkgs.stdenvAdapters.useMoldLinker pkgs.clangStdenv; }
        else
            pkgs.mkShell.override { stdenv = pkgs.clangStdenv; };
    mkWrapper =
        package: wrapper:
        let
            # TO-DO: is this reliable? Should I just take a separate binary name input?
            name = package.pname;
            binPath = "${package}/bin/${name}";
        in
        pkgs.symlinkJoin {
            inherit name;
            paths = [
                (pkgs.writeShellScriptBin name (wrapper binPath))
                package
            ];
        };
    createConfigs =
        let
            mkScript = name: content: "${pkgs.writeShellScriptBin name content}/bin/${name}";
            cargoConfig = ''
                # This file was @generated by `shell.nix`. Do not edit!

                [build]
                target = "${targetTriple}"
            '';
            vscodeConfig = ''
                // This file was @generated by `shell.nix`. Do not edit!

                {
                    "rust-analyzer.cargo.target": "${targetTriple}",
                    "rust-analyzer.cargo.features": [
                        "unstable-gui"
                    ]
                }
            '';
            createConfig = config: dir: filename: ''
                [ -d "$workspace_root/${dir}" ] || mkdir "$workspace_root/${dir}"

                cat << 'EOF' > "$workspace_root/${dir}/${filename}"
                ${config}
                EOF

                cat << 'EOF' >> "$git_dir/info/exclude"
                # @nix
                /${dir}/${filename}
                EOF
            '';
            lockPathExpr = ''"$(git rev-parse --show-toplevel)/.shell.lock"'';
            addToLock = mkScript "increment_lock.sh" ''
                set -euo pipefail

                count_file="$1"
                summand="$2"

                current_count="$(cat "$count_file")"
                new_count=$((current_count + summand))

                echo $new_count | tee "$count_file"
            '';
            init = mkScript "init_lock.sh" ''
                new_count="$(${addToLock} ${lockPathExpr} 1)"
                if [ "$new_count" != 1 ]; then
                    exit
                fi

                workspace_root="$(git rev-parse --show-toplevel)"
                git_dir="$(git rev-parse --git-dir)"

                ${createConfig cargoConfig ".cargo" "config.toml"}
                ${createConfig vscodeConfig ".vscode" "settings.json"}
            '';
            cleanup = mkScript "cleanup_lock.sh" ''
                set -euo pipefail

                workspace_root="$(git rev-parse --show-toplevel)"
                count_file=${lockPathExpr}

                new_count="$(${addToLock} "$count_file" -1)"

                if [ "$new_count" -gt 0 ]; then
                    exit 0
                fi

                rm "$count_file"

                # Find and remove lines precedeed by a marker comment. Also removes the comment.
                sed -ie '/^# @nix/,+1d' "$(git rev-parse --git-dir)/info/exclude"

                # Will remove any local copies. Oh well!
                rm "$workspace_root/.vscode/settings.json"
                # TO-DO: this will have to change to a line-matching solution if I start using
                # `.cargo/config.toml` for any other purpose.
                rm "$workspace_root/.cargo/config.toml"
            '';
        in
        ''
            function cleanup() {
                flock ${lockPathExpr} ${cleanup}
            }
            trap 'cleanup' EXIT

            flock ${lockPathExpr} ${init}
        '';
in
mkShell rec {
    shellHook = createConfigs;
    packages =
        with pkgs;
        [
            clang
            clang-tools
            libclang
            libllvm
            cargo-dist

            # Needed to open the GUI.
            libxkbcommon
            wayland

            # Needed for `rfd` file dialogs.
            #
            # TO-DO: "If you are packaging an application that uses RFD, ensure that both a
            # supported portal backend and Zenity are installed with the package."
            dbus

            # Needed to install Comet.
            pkg-config
            openssl
        ]
        ++ (lib.lists.optional useMold [ pkgs.mold ])
        ++ (lib.lists.optionals (lib.strings.hasSuffix "-msvc" targetTriple) [
            cargo-xwin
            (mkWrapper cargo (
                let
                    xwinSubcommands = [
                        "bench"
                        "build"
                        "b"
                        "check"
                        "c"
                        "clippy"
                        "doc"
                        "d"
                        "env"
                        "run"
                        "r"
                        "rustc"
                        "test"
                        "t"
                        "cache"
                    ];
                    # A list of Cargo options taken before the subcommand that expect to be followed
                    # up with a value. This will need to be updated often!
                    cargoOptionsWithValues = [
                        "--explain"
                        "--config"
                        "-Z"
                        "-C"
                        "--color"
                    ];
                in
                binPath: ''
                    set -euo pipefail

                    args=()
                    while [ $# -gt 0 ]; do
                        arg="$1"
                        shift

                        case "$arg" in
                            ${lib.strings.join " | " cargoOptionsWithValues})
                                value="$1"
                                shift

                                args+=("$arg" "$value")
                                ;;
                            # `+toolchain` matching only works for Cargo installations from rustup,
                            # but it doesn't hurt to match on it here.
                            -* | +*)
                                args+=("$arg")
                                ;;
                            ${lib.strings.join " | " xwinSubcommands})
                                args+=(xwin "$arg" "$@")
                                break
                                ;;
                            noxwin)
                                args+=("$@")
                                break
                                ;;
                            *)
                                args+=("$arg" "$@")
                                break
                                ;;
                        esac
                    done

                    exec '${binPath}' "''${args[@]}"
                ''
            ))
        ]);
    LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath packages;
}
